edition = "2021"
max_width = 100
newline_style = "Auto"
use_small_heuristics = "Default"
tab_spaces = 4
hard_tabs = false
reorder_imports = true
reorder_modules = true
merge_derives = true
use_field_init_shorthand = true
use_try_shorthand = true 